-- this file is generated by program!
-- don't change it manaully.
-- source file: gift_set.xls
-- created at: Tue May 20 12:10:29 2014


local item_container = {}


item_container.type_map = {}
local type_map = item_container.type_map
type_map[2001] = "item_container_2001s"
type_map["item_container_2001s"] = 2001
type_map[2003] = "item_container_2003s"
type_map["item_container_2003s"] = 2003
type_map[2002] = "item_container_2002s"
type_map["item_container_2002s"] = 2002


item_container.item_container_2001s = {}
local item_container_2001s = item_container.item_container_2001s

item_container_2001s[1] = {
	id = 2001,
	name = "item_container_2001",
	item_id = 3001,
	item_weight = 60,
}

item_container_2001s[2] = {
	item_id = 3002,
	item_weight = 30,
}

item_container.item_container_2003s = {}
local item_container_2003s = item_container.item_container_2003s

item_container_2003s[1] = {
	id = 2003,
	name = "item_container_2003",
	item_id = 3005,
	item_weight = 20,
}

item_container_2003s[2] = {
	item_id = 3006,
	item_weight = 30,
}

item_container.item_container_2002s = {}
local item_container_2002s = item_container.item_container_2002s

item_container_2002s[1] = {
	id = 2002,
	name = "item_container_2002",
	item_id = 3003,
	item_weight = 40,
}

item_container_2002s[2] = {
	item_id = 3004,
	item_weight = 75,
}

item_container.type= {}
local type = item_container.type
type[1] = item_container_2001s
type[2] = item_container_2003s
type[3] = item_container_2002s



for i=1, #(item_container.type) do
	local item = item_container.type[i]
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end


return item_container

